changed trivy format to table

diff --git a/.github/workflows/main_pr.yml b/.github/workflows/main_pr.yml
--- a/.github/workflows/main_pr.yml
+++ b/.github/workflows/main_pr.yml
@@ -65,14 +65,15 @@ jobs:
         #   exit-code: '1'
           ignore-unfixed: false
           severity: 'CRITICAL,HIGH'
-          format: 'sarif'
-          output: 'trivy.sarif'
+          format: 'table'
+    #       format: 'sarif'
+    #       output: 'trivy.sarif'
 
-      - name: Upload Trivy scan results to GitHub Security tab
-        uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
-        with:
-          sarif_file: 'trivy.sarif'
+    #   - name: Upload Trivy scan results to GitHub Security tab
+    #     uses: github/codeql-action/upload-sarif@v3
+    #     if: success() || failure()
+    #     with:
+    #       sarif_file: 'trivy.sarif'
 
       - name: OpenTofu Plan
         env:
@@ -132,6 +133,9 @@ jobs:
           name: tofu-plan
           path: tf-bootstrap/tfplan
 
+
+
+
     #   - name: Scan repo with kube-linter
     #     uses: stackrox/kube-linter-action@v1.0.4
     #     with:
@@ -145,11 +149,11 @@ jobs:
     #     with:
     #       sarif_file: kube-linter.sarif
 
-      - name: Setup Golang
-        uses: actions/setup-go@v5
+    #   - name: Setup Golang
+    #     uses: actions/setup-go@v5
 
-      - name: Setup Kubeconform
-        run: go install github.com/yannh/kubeconform/cmd/kubeconform@v0.6.7
+    #   - name: Setup Kubeconform
+    #     run: go install github.com/yannh/kubeconform/cmd/kubeconform@v0.6.7
 
-      - name: Run Flux validation script
-        run: curl https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/scripts/validate.sh | bash
+    #   - name: Run Flux validation script
+    #     run: curl https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/scripts/validate.sh | bash
